import Head from 'next/head'
import Link from "next/link";
import type { InferGetServerSidePropsType, GetServerSideProps } from 'next'
//import { Inter } from '@next/font/google'
//import styles from '../styles/Home.module.sass'

//const inter = Inter({ subsets: ['latin'] })

type Product = {
  name: string
  stargazers_count: number
}
 
export const getServerSideProps: GetServerSideProps<{products: Product}> = async () => {
  const res = await fetch('https://api.github.com/repos/vercel/next.js')
  const products = await res.json()
  return { props: { products } }
}

export default function Home({products}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>EXCELSIOR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="flex-col px-4 md:px-24 items-center pt-48">
          <p>{products.stargazers_count}</p>
          <article className='hero gap-4 h-min'>
            <Link href='/'>
              <img src="https://cdn.discordapp.com/attachments/911206419280314442/1125888270367211530/product.png" alt="" className='w-full h-full object-cover hover:scale-105'/>
            </Link>
            <Link href='/'>
              <img src="https://cdn.discordapp.com/attachments/911206419280314442/1125888270367211530/product.png" alt="" className='w-full h-full object-cover hover:scale-105'/>
            </Link>
            <Link href='/'>
              <img src="https://cdn.discordapp.com/attachments/911206419280314442/1125888270367211530/product.png" alt="" className='w-full h-full object-cover hover:scale-105'/>
            </Link>
            <Link href='/'>
              <img src="https://cdn.discordapp.com/attachments/911206419280314442/1125888270367211530/product.png" alt="" className='w-full h-full object-cover hover:scale-105'/>
            </Link>
            <div className='flex h-100'>
              <h1 className='text-6xl md:text-8xl leading-[4rem] self-end'>40%<br/><span className='text-5xl md:text-6xl'>Discount</span></h1>
              <h3 className='uppercase ml-auto text-end'>
                Full Size<br/>
                Sample Size<br/>
                Single-Serve<br/>
                11g (0.4 Oz)
              </h3>
            </div>
            <div className='overflow-hidden'>
              <h2 className='text-end text-3xl'>Our selection of coffee and filters</h2>
              <img className='mix-blend-multiply scale-[2] pointer-events-none' src="https://cdn.discordapp.com/attachments/911206419280314442/1126235534973468682/Frame_11.png" alt="" />
            </div>
          </article>
          <h2 className='text-center text-3xl mt-24 mb-12'>Pick your brewer of selection</h2>
          <article className='hero gap-4 h-min mt-auto'>
            <div>
              <img className='mix-blend-multiply md:scale-150 pointer-events-none' src="https://cdn.discordapp.com/attachments/911206419280314442/1126296592413118594/Frame_12.png" alt="" />
            </div>
            <Link href='/'>
              <img src="https://cdn.discordapp.com/attachments/911206419280314442/1125888270367211530/product.png" alt="" className='w-full h-full object-cover hover:scale-105'/>
            </Link>
            <Link href='/'>
              <img src="https://cdn.discordapp.com/attachments/911206419280314442/1125888270367211530/product.png" alt="" className='w-full h-full object-cover hover:scale-105'/>
            </Link>
            <Link href='/'>
              <img src="https://cdn.discordapp.com/attachments/911206419280314442/1125888270367211530/product.png" alt="" className='w-full h-full object-cover hover:scale-105'/>
            </Link>
            <div className='flex h-100'>
              <h1 className='text-8xl leading-[4rem] self-end text-end ml-auto'>25%<br/><span className='text-6xl'>Discount</span></h1>
            </div>
            <Link href='/'>
              <img src="https://cdn.discordapp.com/attachments/911206419280314442/1125888270367211530/product.png" alt="" className='w-full h-full object-cover hover:scale-105'/>
            </Link>
          </article>
        </section>
        <section className='flex-col pt-48 items-center pb-28'>
          <h1 className='text-center text-3xl'>The complete <span className='logo'>EXCELSIOR</span> catalog</h1>
          <div className='grid grid-cols-1 md:grid-cols-3 gap-4 w-96 mt-24 px-12'>
          {
            [1,2,34,5,6,7,5,6,7,8,5,34,3,2,34,4].map(item => {
              return (
              <Link href='/' className='border-none p-0'>
                <img src="https://cdn.discordapp.com/attachments/911206419280314442/1125888270367211530/product.png" alt="" className='w-full h-full object-cover hover:scale-105'/>
              </Link>
              )
            })
          }
          </div>
        </section>
      </main>
    </>
  )
}
